version: '3.1'

services:
  blog_server:
    build: ../go/blog/blog_server
    ports:
      - "50051:50051"
    depends_on:
      - mongo
  blog_client:
    build: ../go/blog/blog_client
    depends_on:
      - blog_server
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=mydb