version: '3.1'

services:
  greet_server:
    build: ../go/greet/server
    ports:
      - "50051:50051"
  greet_client:
    build: ../go/greet/client
    command: ["sh", "-c" ,"./greetclient -server_host=greet_server"]
    depends_on:
      - greet_server