version: '3.4'

services:
  # rust_server:
  #   build: rust
  #   command: ["/usr/local/bin/rust_server", "127.0.0.1:50051"]
  #   ports:
  #     - "50051:50051"
  #   networks:
  #     - basic-network
  
  rust_client:
    build: rust
    command: ["/usr/local/bin/rust_client", "http://go_server:50051"]
    depends_on:
      - go_server
    networks:
      - basic-network

  go_server:
    build: go_server
    ports:
      - "50051:50051"

  go_client:
    build: go_client
    command: ["sh", "-c" ,"./basicgoclient -server_host=go_server"]
    networks:
      - basic-network
    depends_on:
      - go_server

networks:
 basic-network: